export const demoData = {
  company: {
    name: 'Maison Aura',
    industry: 'Luxury Fragrance',
    founded: 2019,
    employees: 48,
    arr: 4800000,
  },

  formulas: [
    { id: 'f-001', name: 'Solaire de Nuit', status: 'In Review', category: 'Eau de Parfum', ingredients: 42, costPerKg: 52.40, ifraScore: 94, performanceScore: 87, createdAt: '2026-06-01', updatedAt: '2026-06-28', author: 'Sarah Chen' },
    { id: 'f-002', name: 'Jardin Céleste', status: 'Approved', category: 'Eau de Toilette', ingredients: 38, costPerKg: 41.20, ifraScore: 97, performanceScore: 92, createdAt: '2026-05-15', updatedAt: '2026-06-25', author: 'Sarah Chen' },
    { id: 'f-003', name: 'Ambre Révélation', status: 'Draft', category: 'Eau de Parfum', ingredients: 56, costPerKg: 68.90, ifraScore: 88, performanceScore: 79, createdAt: '2026-06-20', updatedAt: '2026-06-29', author: 'Marcus Webb' },
    { id: 'f-004', name: 'Brise Méditerranéenne', status: 'Approved', category: 'Eau de Cologne', ingredients: 29, costPerKg: 33.60, ifraScore: 99, performanceScore: 91, createdAt: '2026-04-10', updatedAt: '2026-06-15', author: 'Olivia Tanaka' },
    { id: 'f-005', name: 'Cuir Impérial', status: 'In Review', category: 'Extrait', ingredients: 64, costPerKg: 89.30, ifraScore: 86, performanceScore: 93, createdAt: '2026-06-05', updatedAt: '2026-06-28', author: 'Sarah Chen' },
    { id: 'f-006', name: 'Nuit Étoilée', status: 'Approved', category: 'Eau de Parfum', ingredients: 45, costPerKg: 55.80, ifraScore: 95, performanceScore: 90, createdAt: '2026-03-01', updatedAt: '2026-06-20', author: 'James Park' },
    { id: 'f-007', name: 'Fleur de Nacre', status: 'Draft', category: 'Eau de Toilette', ingredients: 34, costPerKg: 38.40, ifraScore: 92, performanceScore: 84, createdAt: '2026-06-25', updatedAt: '2026-06-29', author: 'Olivia Tanaka' },
    { id: 'f-008', name: 'Bois Mystique', status: 'Rejected', category: 'Eau de Parfum', ingredients: 48, costPerKg: 61.20, ifraScore: 72, performanceScore: 65, createdAt: '2026-05-20', updatedAt: '2026-06-22', author: 'Marcus Webb' },
    { id: 'f-009', name: 'Vanille des Îles', status: 'Approved', category: 'Eau de Parfum', ingredients: 36, costPerKg: 47.90, ifraScore: 96, performanceScore: 94, createdAt: '2026-02-14', updatedAt: '2026-06-18', author: 'Sarah Chen' },
    { id: 'f-010', name: 'Oud Royale', status: 'In Review', category: 'Extrait', ingredients: 72, costPerKg: 145.00, ifraScore: 84, performanceScore: 96, createdAt: '2026-06-10', updatedAt: '2026-06-29', author: 'Marcus Webb' },
    { id: 'f-011', name: 'Eau de Lune', status: 'Approved', category: 'Eau de Toilette', ingredients: 31, costPerKg: 36.50, ifraScore: 98, performanceScore: 89, createdAt: '2026-01-05', updatedAt: '2026-06-12', author: 'Olivia Tanaka' },
    { id: 'f-012', name: 'Santal Éternel', status: 'Draft', category: 'Eau de Parfum', ingredients: 52, costPerKg: 73.60, ifraScore: 90, performanceScore: 85, createdAt: '2026-06-28', updatedAt: '2026-06-29', author: 'James Park' },
    { id: 'f-013', name: 'Agrumes de Sicile', status: 'In Review', category: 'Eau de Cologne', ingredients: 26, costPerKg: 28.90, ifraScore: 97, performanceScore: 83, createdAt: '2026-06-18', updatedAt: '2026-06-27', author: 'Olivia Tanaka' },
    { id: 'f-014', name: 'Rose de Damas', status: 'Approved', category: 'Eau de Parfum', ingredients: 40, costPerKg: 58.30, ifraScore: 93, performanceScore: 95, createdAt: '2026-04-22', updatedAt: '2026-06-10', author: 'Sarah Chen' },
    { id: 'f-015', name: 'Encens Sacré', status: 'Approved', category: 'Extrait', ingredients: 58, costPerKg: 92.10, ifraScore: 91, performanceScore: 97, createdAt: '2026-03-15', updatedAt: '2026-06-08', author: 'Marcus Webb' },
    { id: 'f-016', name: 'Iris d\'Or', status: 'Draft', category: 'Eau de Parfum', ingredients: 44, costPerKg: 65.20, ifraScore: 89, performanceScore: 82, createdAt: '2026-06-22', updatedAt: '2026-06-29', author: 'Sarah Chen' },
    { id: 'f-017', name: 'Miel d\'Acacia', status: 'In Review', category: 'Eau de Toilette', ingredients: 33, costPerKg: 39.80, ifraScore: 95, performanceScore: 86, createdAt: '2026-06-12', updatedAt: '2026-06-26', author: 'James Park' },
    { id: 'f-018', name: 'Vétiver Océan', status: 'Approved', category: 'Eau de Toilette', ingredients: 35, costPerKg: 42.50, ifraScore: 96, performanceScore: 88, createdAt: '2026-05-01', updatedAt: '2026-06-05', author: 'Olivia Tanaka' },
    { id: 'f-019', name: 'Tabac Doré', status: 'In Review', category: 'Eau de Parfum', ingredients: 50, costPerKg: 71.40, ifraScore: 87, performanceScore: 91, createdAt: '2026-06-08', updatedAt: '2026-06-29', author: 'Marcus Webb' },
    { id: 'f-020', name: 'Fougère Sauvage', status: 'Draft', category: 'Eau de Cologne', ingredients: 28, costPerKg: 31.60, ifraScore: 93, performanceScore: 80, createdAt: '2026-06-27', updatedAt: '2026-06-29', author: 'Olivia Tanaka' },
    { id: 'f-021', name: 'Musc Blanc', status: 'Approved', category: 'Eau de Parfum', ingredients: 39, costPerKg: 49.30, ifraScore: 98, performanceScore: 93, createdAt: '2026-02-28', updatedAt: '2026-05-30', author: 'Sarah Chen' },
    { id: 'f-022', name: 'Thé Vert Matinal', status: 'Approved', category: 'Eau de Toilette', ingredients: 30, costPerKg: 34.70, ifraScore: 99, performanceScore: 87, createdAt: '2026-04-05', updatedAt: '2026-05-25', author: 'James Park' },
    { id: 'f-023', name: 'Cèdre Noir', status: 'In Review', category: 'Eau de Parfum', ingredients: 46, costPerKg: 57.80, ifraScore: 91, performanceScore: 89, createdAt: '2026-06-14', updatedAt: '2026-06-28', author: 'Marcus Webb' },
    { id: 'f-024', name: 'Patchouli Intense', status: 'Draft', category: 'Extrait', ingredients: 60, costPerKg: 82.50, ifraScore: 85, performanceScore: 90, createdAt: '2026-06-26', updatedAt: '2026-06-29', author: 'Sarah Chen' },
    { id: 'f-025', name: 'Néroli d\'Été', status: 'Approved', category: 'Eau de Cologne', ingredients: 27, costPerKg: 29.40, ifraScore: 97, performanceScore: 84, createdAt: '2026-03-20', updatedAt: '2026-05-20', author: 'Olivia Tanaka' },
    { id: 'f-026', name: 'Ambre Gris', status: 'Rejected', category: 'Eau de Parfum', ingredients: 54, costPerKg: 76.90, ifraScore: 68, performanceScore: 62, createdAt: '2026-05-10', updatedAt: '2026-06-01', author: 'James Park' },
    { id: 'f-027', name: 'Jasmin Nuit', status: 'Approved', category: 'Eau de Parfum', ingredients: 41, costPerKg: 54.60, ifraScore: 94, performanceScore: 96, createdAt: '2026-01-20', updatedAt: '2026-04-15', author: 'Sarah Chen' },
    { id: 'f-028', name: 'Gingembre Frais', status: 'In Review', category: 'Eau de Cologne', ingredients: 25, costPerKg: 26.30, ifraScore: 96, performanceScore: 81, createdAt: '2026-06-16', updatedAt: '2026-06-27', author: 'Olivia Tanaka' },
    { id: 'f-029', name: 'Badiane de Chine', status: 'Draft', category: 'Eau de Parfum', ingredients: 47, costPerKg: 59.20, ifraScore: 88, performanceScore: 83, createdAt: '2026-06-24', updatedAt: '2026-06-29', author: 'Marcus Webb' },
    { id: 'f-030', name: 'Benjoin Rêverie', status: 'Approved', category: 'Eau de Parfum', ingredients: 43, costPerKg: 62.80, ifraScore: 92, performanceScore: 91, createdAt: '2026-02-10', updatedAt: '2026-04-10', author: 'Sarah Chen' },
    { id: 'f-031', name: 'Ylang des Comores', status: 'In Review', category: 'Eau de Toilette', ingredients: 37, costPerKg: 43.90, ifraScore: 90, performanceScore: 85, createdAt: '2026-06-06', updatedAt: '2026-06-28', author: 'James Park' },
    { id: 'f-032', name: 'Cannelle Noël', status: 'Draft', category: 'Eau de Cologne', ingredients: 32, costPerKg: 35.10, ifraScore: 86, performanceScore: 78, createdAt: '2026-06-29', updatedAt: '2026-06-29', author: 'Olivia Tanaka' },
    { id: 'f-033', name: 'Labdanum Antique', status: 'Approved', category: 'Extrait', ingredients: 62, costPerKg: 95.40, ifraScore: 89, performanceScore: 95, createdAt: '2026-04-18', updatedAt: '2026-06-02', author: 'Marcus Webb' },
    { id: 'f-034', name: 'Bergamote de Calabre', status: 'Approved', category: 'Eau de Cologne', ingredients: 24, costPerKg: 27.80, ifraScore: 100, performanceScore: 86, createdAt: '2026-03-05', updatedAt: '2026-05-05', author: 'Olivia Tanaka' },
    { id: 'f-035', name: 'Géranium Bourbon', status: 'In Review', category: 'Eau de Toilette', ingredients: 36, costPerKg: 40.50, ifraScore: 93, performanceScore: 88, createdAt: '2026-06-09', updatedAt: '2026-06-28', author: 'Sarah Chen' },
    { id: 'f-036', name: 'Lavande de Haute-Provence', status: 'Approved', category: 'Eau de Cologne', ingredients: 23, costPerKg: 25.90, ifraScore: 99, performanceScore: 90, createdAt: '2026-01-15', updatedAt: '2026-03-20', author: 'Olivia Tanaka' },
    { id: 'f-037', name: 'Safran d\'Ispahan', status: 'Draft', category: 'Eau de Parfum', ingredients: 51, costPerKg: 78.30, ifraScore: 83, performanceScore: 81, createdAt: '2026-06-23', updatedAt: '2026-06-29', author: 'James Park' },
    { id: 'f-038', name: 'Myrrhe d\'Oman', status: 'Approved', category: 'Extrait', ingredients: 66, costPerKg: 98.70, ifraScore: 87, performanceScore: 94, createdAt: '2026-05-25', updatedAt: '2026-06-25', author: 'Marcus Webb' },
    { id: 'f-039', name: 'Coriandre Verte', status: 'In Review', category: 'Eau de Toilette', ingredients: 32, costPerKg: 37.60, ifraScore: 95, performanceScore: 82, createdAt: '2026-06-13', updatedAt: '2026-06-27', author: 'Olivia Tanaka' },
    { id: 'f-040', name: 'Poivre Noir de Malabar', status: 'Approved', category: 'Eau de Parfum', ingredients: 44, costPerKg: 56.10, ifraScore: 92, performanceScore: 89, createdAt: '2026-04-28', updatedAt: '2026-06-14', author: 'Marcus Webb' },
    { id: 'f-041', name: 'Fève Tonka d\'Amazonie', status: 'Draft', category: 'Eau de Parfum', ingredients: 49, costPerKg: 66.40, ifraScore: 84, performanceScore: 86, createdAt: '2026-06-21', updatedAt: '2026-06-29', author: 'Sarah Chen' },
    { id: 'f-042', name: 'Bois de Santal Australien', status: 'In Review', category: 'Eau de Parfum', ingredients: 53, costPerKg: 70.80, ifraScore: 90, performanceScore: 92, createdAt: '2026-06-11', updatedAt: '2026-06-29', author: 'James Park' },
    { id: 'f-043', name: 'Aldéhyde Floral', status: 'Approved', category: 'Eau de Toilette', ingredients: 35, costPerKg: 39.20, ifraScore: 96, performanceScore: 87, createdAt: '2026-05-08', updatedAt: '2026-06-22', author: 'Sarah Chen' },
    { id: 'f-044', name: 'Cuir de Russie', status: 'Draft', category: 'Extrait', ingredients: 68, costPerKg: 105.30, ifraScore: 81, performanceScore: 88, createdAt: '2026-06-30', updatedAt: '2026-06-30', author: 'Marcus Webb' },
    { id: 'f-045', name: 'Muguet des Bois', status: 'Approved', category: 'Eau de Toilette', ingredients: 30, costPerKg: 35.80, ifraScore: 98, performanceScore: 85, createdAt: '2026-02-20', updatedAt: '2026-04-28', author: 'Olivia Tanaka' },
    { id: 'f-046', name: 'Tubéreuse de Madagascar', status: 'In Review', category: 'Eau de Parfum', ingredients: 46, costPerKg: 60.50, ifraScore: 91, performanceScore: 93, createdAt: '2026-06-15', updatedAt: '2026-06-29', author: 'Sarah Chen' },
    { id: 'f-047', name: 'Citron de Menton', status: 'Approved', category: 'Eau de Cologne', ingredients: 22, costPerKg: 24.60, ifraScore: 100, performanceScore: 82, createdAt: '2026-03-25', updatedAt: '2026-05-15', author: 'Olivia Tanaka' },
    { id: 'f-048', name: 'Osmanthus de Chine', status: 'Draft', category: 'Eau de Parfum', ingredients: 41, costPerKg: 63.20, ifraScore: 87, performanceScore: 84, createdAt: '2026-06-26', updatedAt: '2026-06-29', author: 'James Park' },
    { id: 'f-049', name: 'Héliotrope Blanc', status: 'Approved', category: 'Eau de Toilette', ingredients: 33, costPerKg: 38.10, ifraScore: 94, performanceScore: 86, createdAt: '2026-04-15', updatedAt: '2026-06-10', author: 'Sarah Chen' },
    { id: 'f-050', name: 'Ambreine Suave', status: 'In Review', category: 'Eau de Parfum', ingredients: 48, costPerKg: 67.30, ifraScore: 89, performanceScore: 90, createdAt: '2026-06-17', updatedAt: '2026-06-29', author: 'Marcus Webb' },
    { id: 'f-051', name: 'Lotus d\'Orient', status: 'Draft', category: 'Eau de Parfum', ingredients: 43, costPerKg: 58.90, ifraScore: 86, performanceScore: 80, createdAt: '2026-06-29', updatedAt: '2026-06-29', author: 'Olivia Tanaka' },
    { id: 'f-052', name: 'Magnolia du Sud', status: 'Approved', category: 'Eau de Toilette', ingredients: 34, costPerKg: 40.20, ifraScore: 95, performanceScore: 88, createdAt: '2026-05-12', updatedAt: '2026-06-20', author: 'Sarah Chen' },
  ],

  materials: [
    { id: 'm-001', name: 'Bergamot Essential Oil', cas: '8000-27-9', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.12, ifraMax: 15, natural: true, inStock: true },
    { id: 'm-002', name: 'Lemon Essential Oil', cas: '8008-56-8', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.09, ifraMax: 20, natural: true, inStock: true },
    { id: 'm-003', name: 'Orange Sweet Essential Oil', cas: '8008-57-9', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.06, ifraMax: 25, natural: true, inStock: true },
    { id: 'm-004', name: 'Grapefruit Essential Oil', cas: '8016-20-4', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.11, ifraMax: 18, natural: true, inStock: true },
    { id: 'm-005', name: 'Mandarin Essential Oil', cas: '8008-31-9', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.10, ifraMax: 22, natural: true, inStock: true },
    { id: 'm-006', name: 'Lime Essential Oil', cas: '8008-26-2', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.13, ifraMax: 16, natural: true, inStock: true },
    { id: 'm-007', name: 'Lavender Essential Oil', cas: '8000-28-0', category: 'Top Notes', odorFamily: 'Herbal', costPerGram: 0.15, ifraMax: 20, natural: true, inStock: true },
    { id: 'm-008', name: 'Rosemary Essential Oil', cas: '8000-25-7', category: 'Top Notes', odorFamily: 'Herbal', costPerGram: 0.14, ifraMax: 18, natural: true, inStock: true },
    { id: 'm-009', name: 'Peppermint Essential Oil', cas: '8006-90-4', category: 'Top Notes', odorFamily: 'Minty', costPerGram: 0.18, ifraMax: 15, natural: true, inStock: true },
    { id: 'm-010', name: 'Eucalyptus Essential Oil', cas: '8000-48-4', category: 'Top Notes', odorFamily: 'Herbal', costPerGram: 0.12, ifraMax: 12, natural: true, inStock: true },
    { id: 'm-011', name: 'Jasmine Absolute', cas: '8022-96-6', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.85, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-012', name: 'Rose Absolute', cas: '8007-01-0', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 1.20, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-013', name: 'Ylang Ylang Essential Oil', cas: '8006-81-3', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.45, ifraMax: 10, natural: true, inStock: true },
    { id: 'm-014', name: 'Geranium Essential Oil', cas: '8000-46-2', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.38, ifraMax: 12, natural: true, inStock: true },
    { id: 'm-015', name: 'Neroli Essential Oil', cas: '8016-38-4', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 2.40, ifraMax: 5, natural: true, inStock: true },
    { id: 'm-016', name: 'Clary Sage Essential Oil', cas: '8016-63-5', category: 'Heart Notes', odorFamily: 'Herbal', costPerGram: 0.32, ifraMax: 14, natural: true, inStock: true },
    { id: 'm-017', name: 'Coriander Seed Essential Oil', cas: '8008-52-4', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.28, ifraMax: 16, natural: true, inStock: true },
    { id: 'm-018', name: 'Cinnamon Bark Essential Oil', cas: '8015-91-6', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.55, ifraMax: 3, natural: true, inStock: true },
    { id: 'm-019', name: 'Clove Bud Essential Oil', cas: '8000-34-8', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.25, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-020', name: 'Nutmeg Essential Oil', cas: '8008-45-5', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.30, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-021', name: 'Cardamom Essential Oil', cas: '8000-66-6', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.65, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-022', name: 'Black Pepper Essential Oil', cas: '8006-82-4', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.22, ifraMax: 10, natural: true, inStock: true },
    { id: 'm-023', name: 'Sandalwood Essential Oil', cas: '8006-87-9', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 4.50, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-024', name: 'Cedarwood Essential Oil', cas: '8000-27-2', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.18, ifraMax: 15, natural: true, inStock: true },
    { id: 'm-025', name: 'Patchouli Essential Oil', cas: '8016-62-4', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.35, ifraMax: 12, natural: true, inStock: true },
    { id: 'm-026', name: 'Vetiver Essential Oil', cas: '8016-96-4', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.80, ifraMax: 10, natural: true, inStock: true },
    { id: 'm-027', name: 'Oakmoss Absolute', cas: '9000-50-4', category: 'Base Notes', odorFamily: 'Earthy', costPerGram: 0.95, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-028', name: 'Vanilla Absolute', cas: '8024-06-4', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 2.80, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-029', name: 'Tonka Bean Absolute', cas: '8046-22-8', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 1.50, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-030', name: 'Benzoin Resinoid', cas: '9000-05-9', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.60, ifraMax: 12, natural: true, inStock: true },
    { id: 'm-031', name: 'Labdanum Absolute', cas: '8016-26-0', category: 'Base Notes', odorFamily: 'Amber', costPerGram: 1.10, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-032', name: 'Ambergris Synthetic', cas: '100-42-5', category: 'Base Notes', odorFamily: 'Amber', costPerGram: 0.45, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-033', name: 'Musk Ketone', cas: '81-14-1', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.20, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-034', name: 'Musk Xylene', cas: '81-15-2', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.18, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-035', name: 'Ethylene Brassylate', cas: '105-95-3', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.15, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-036', name: 'Galaxolide 50', cas: '1222-05-5', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.12, ifraMax: 25, natural: false, inStock: true },
    { id: 'm-037', name: 'Iso E Super', cas: '54464-57-2', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.08, ifraMax: 30, natural: false, inStock: true },
    { id: 'm-038', name: 'Hedione', cas: '24851-98-7', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.06, ifraMax: 25, natural: false, inStock: true },
    { id: 'm-039', name: 'Linalool', cas: '78-70-6', category: 'Top Notes', odorFamily: 'Floral', costPerGram: 0.04, ifraMax: 30, natural: false, inStock: true },
    { id: 'm-040', name: 'Coumarin', cas: '91-64-5', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.05, ifraMax: 15, natural: false, inStock: true },
    { id: 'm-041', name: 'Ethyl Vanillin', cas: '121-32-4', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.35, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-042', name: 'Methyl Ionone', cas: '1335-46-2', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.10, ifraMax: 18, natural: false, inStock: true },
    { id: 'm-043', name: 'Allyl Amyl Glycolate', cas: '67634-00-8', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.15, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-044', name: 'Terpinyl Acetate', cas: '8007-35-0', category: 'Heart Notes', odorFamily: 'Woody', costPerGram: 0.08, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-045', name: 'Benzyl Acetate', cas: '140-11-4', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.05, ifraMax: 22, natural: false, inStock: true },
    { id: 'm-046', name: 'Phenethyl Alcohol', cas: '60-12-8', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.06, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-047', name: 'Alpha-Terpineol', cas: '98-55-5', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.07, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-048', name: 'Citronellol', cas: '106-22-9', category: 'Heart Notes', odorFamily: 'Citrus', costPerGram: 0.06, ifraMax: 18, natural: false, inStock: true },
    { id: 'm-049', name: 'Geraniol', cas: '106-24-1', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.05, ifraMax: 18, natural: false, inStock: true },
    { id: 'm-050', name: 'Eugenol', cas: '97-53-0', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.08, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-051', name: 'Isoamyl Acetate', cas: '123-92-2', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.04, ifraMax: 15, natural: false, inStock: true },
    { id: 'm-052', name: 'Ethyl Butyrate', cas: '105-54-4', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.03, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-053', name: 'Ethyl Acetate', cas: '141-78-6', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.02, ifraMax: 30, natural: false, inStock: true },
    { id: 'm-054', name: 'Dipropylene Glycol', cas: '25265-71-8', category: 'Solvents', odorFamily: 'Odorless', costPerGram: 0.01, ifraMax: 100, natural: false, inStock: true },
    { id: 'm-055', name: 'Triethyl Citrate', cas: '77-93-0', category: 'Solvents', odorFamily: 'Odorless', costPerGram: 0.02, ifraMax: 100, natural: false, inStock: true },
    { id: 'm-056', name: 'Benzyl Benzoate', cas: '120-51-4', category: 'Solvents', odorFamily: 'Odorless', costPerGram: 0.03, ifraMax: 40, natural: false, inStock: true },
    { id: 'm-057', name: 'Farnesol', cas: '4602-84-0', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.12, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-058', name: 'Lilial', cas: '80-54-6', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.09, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-059', name: 'Lyral', cas: '31906-04-4', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.11, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-060', name: 'Helional', cas: '1205-17-0', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.14, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-061', name: 'Calone 1951', cas: '28940-89-0', category: 'Top Notes', odorFamily: 'Fresh', costPerGram: 0.45, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-062', name: 'Floralozone', cas: '67634-15-5', category: 'Top Notes', odorFamily: 'Fresh', costPerGram: 0.18, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-063', name: 'Precyclemone B', cas: '67634-14-4', category: 'Top Notes', odorFamily: 'Fresh', costPerGram: 0.22, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-064', name: 'Scentenal', cas: '86803-90-9', category: 'Top Notes', odorFamily: 'Fresh', costPerGram: 0.55, ifraMax: 3, natural: false, inStock: true },
    { id: 'm-065', name: 'Triplal', cas: '67634-00-8', category: 'Top Notes', odorFamily: 'Green', costPerGram: 0.16, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-066', name: 'Stemone', cas: '57743-63-2', category: 'Top Notes', odorFamily: 'Green', costPerGram: 0.20, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-067', name: 'Verdox', cas: '36265-41-5', category: 'Heart Notes', odorFamily: 'Green', costPerGram: 0.12, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-068', name: 'Cis-3-Hexenol', cas: '928-96-1', category: 'Top Notes', odorFamily: 'Green', costPerGram: 0.30, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-069', name: 'Damascenone Alpha', cas: '23696-85-7', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 2.80, ifraMax: 2, natural: false, inStock: true },
    { id: 'm-070', name: 'Damascenone Beta', cas: '23726-93-4', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 3.20, ifraMax: 1.5, natural: false, inStock: true },
    { id: 'm-071', name: 'Ionone Alpha', cas: '127-41-3', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.08, ifraMax: 18, natural: false, inStock: true },
    { id: 'm-072', name: 'Ionone Beta', cas: '79-77-6', category: 'Heart Notes', odorFamily: 'Woody', costPerGram: 0.09, ifraMax: 16, natural: false, inStock: true },
    { id: 'm-073', name: 'Methyl Anthranilate', cas: '134-20-3', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.10, ifraMax: 14, natural: false, inStock: true },
    { id: 'm-074', name: 'Dimethyl Anthranilate', cas: '85-91-6', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.12, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-075', name: 'Aurantiol', cas: '89-43-0', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.15, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-076', name: 'Lyral', cas: '31906-04-4', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.11, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-077', name: 'Bourgeonal', cas: '18127-01-0', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.18, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-078', name: 'Cyclamen Aldehyde', cas: '103-95-7', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.14, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-079', name: 'Lilial', cas: '80-54-6', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.09, ifraMax: 14, natural: false, inStock: true },
    { id: 'm-080', name: 'Vanillin', cas: '121-33-5', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.07, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-081', name: 'Ethyl Maltol', cas: '4940-11-8', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.15, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-082', name: 'Furaneol', cas: '3658-77-3', category: 'Heart Notes', odorFamily: 'Sweet', costPerGram: 1.80, ifraMax: 3, natural: false, inStock: true },
    { id: 'm-083', name: 'Maple Lactone', cas: '706-14-9', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.40, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-084', name: 'Coconut Aldehyde', cas: '5579-78-2', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.35, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-085', name: 'Peach Aldehyde', cas: '121-32-4', category: 'Heart Notes', odorFamily: 'Fruity', costPerGram: 0.25, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-086', name: 'Strawberry Aldehyde', cas: '5392-40-5', category: 'Heart Notes', odorFamily: 'Fruity', costPerGram: 0.20, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-087', name: 'Apple Aldehyde', cas: '142-83-6', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.15, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-088', name: 'Green Apple Aldehyde', cas: '35158-25-9', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.18, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-089', name: 'Methyl Octine Carbonate', cas: '111-12-6', category: 'Top Notes', odorFamily: 'Green', costPerGram: 1.20, ifraMax: 2, natural: false, inStock: true },
    { id: 'm-090', name: 'Violet Leaf Absolute', cas: '8024-09-7', category: 'Heart Notes', odorFamily: 'Green', costPerGram: 3.50, ifraMax: 2, natural: true, inStock: true },
    { id: 'm-091', name: 'Tuberose Absolute', cas: '8024-09-7', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 3.80, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-092', name: 'Narcissus Absolute', cas: '8023-75-4', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 4.20, ifraMax: 3, natural: true, inStock: true },
    { id: 'm-093', name: 'Hyacinth Absolute', cas: '8023-71-0', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 2.90, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-094', name: 'Lilac Absolute', cas: '8023-69-6', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 3.10, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-095', name: 'Mimosa Absolute', cas: '8031-03-6', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 1.60, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-096', name: 'Orris Root Concrete', cas: '8002-73-1', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 8.50, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-097', name: 'Cassis Bud Absolute', cas: '8022-89-5', category: 'Top Notes', odorFamily: 'Green', costPerGram: 2.20, ifraMax: 3, natural: true, inStock: true },
    { id: 'm-098', name: 'Angelica Root Essential Oil', cas: '8015-64-3', category: 'Heart Notes', odorFamily: 'Earthy', costPerGram: 1.40, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-099', name: 'Coriander Leaf Essential Oil', cas: '8008-52-4', category: 'Top Notes', odorFamily: 'Green', costPerGram: 0.28, ifraMax: 10, natural: true, inStock: true },
    { id: 'm-100', name: 'Basil Essential Oil', cas: '8015-73-4', category: 'Top Notes', odorFamily: 'Herbal', costPerGram: 0.20, ifraMax: 12, natural: true, inStock: true },
    { id: 'm-101', name: 'Tarragon Essential Oil', cas: '8016-88-4', category: 'Heart Notes', odorFamily: 'Herbal', costPerGram: 0.35, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-102', name: 'Dill Seed Essential Oil', cas: '8006-75-5', category: 'Top Notes', odorFamily: 'Herbal', costPerGram: 0.25, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-103', name: 'Caraway Essential Oil', cas: '8000-42-8', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.30, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-104', name: 'Cumin Seed Essential Oil', cas: '8014-13-9', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.40, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-105', name: 'Anise Star Essential Oil', cas: '8007-70-3', category: 'Heart Notes', odorFamily: 'Sweet', costPerGram: 0.32, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-106', name: 'Fennel Sweet Essential Oil', cas: '8006-84-6', category: 'Heart Notes', odorFamily: 'Sweet', costPerGram: 0.28, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-107', name: 'Galbanum Resinoid', cas: '9000-24-2', category: 'Top Notes', odorFamily: 'Green', costPerGram: 0.75, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-108', name: 'Myrrh Resinoid', cas: '9000-45-7', category: 'Base Notes', odorFamily: 'Amber', costPerGram: 1.20, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-109', name: 'Frankincense Resinoid', cas: '8050-07-5', category: 'Base Notes', odorFamily: 'Amber', costPerGram: 1.50, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-110', name: 'Opopanax Resinoid', cas: '9000-78-6', category: 'Base Notes', odorFamily: 'Amber', costPerGram: 0.90, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-111', name: 'Peru Balsam Resinoid', cas: '8007-44-1', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.55, ifraMax: 5, natural: true, inStock: true },
    { id: 'm-112', name: 'Tolu Balsam Resinoid', cas: '8013-12-5', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.48, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-113', name: 'Cistus Absolute', cas: '8016-26-0', category: 'Base Notes', odorFamily: 'Amber', costPerGram: 1.30, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-114', name: 'Immortelle Absolute', cas: '8023-95-8', category: 'Heart Notes', odorFamily: 'Sweet', costPerGram: 3.60, ifraMax: 3, natural: true, inStock: true },
    { id: 'm-115', name: 'Davana Essential Oil', cas: '8016-03-3', category: 'Heart Notes', odorFamily: 'Fruity', costPerGram: 2.80, ifraMax: 3, natural: true, inStock: true },
    { id: 'm-116', name: 'Chamomile Roman Essential Oil', cas: '8015-92-7', category: 'Heart Notes', odorFamily: 'Herbal', costPerGram: 0.85, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-117', name: 'Chamomile German Essential Oil', cas: '8002-66-2', category: 'Heart Notes', odorFamily: 'Herbal', costPerGram: 0.90, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-118', name: 'Hyssop Essential Oil', cas: '8006-83-5', category: 'Heart Notes', odorFamily: 'Herbal', costPerGram: 0.45, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-119', name: 'Marjoram Essential Oil', cas: '8015-01-8', category: 'Heart Notes', odorFamily: 'Herbal', costPerGram: 0.30, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-120', name: 'Oregano Essential Oil', cas: '8007-11-2', category: 'Heart Notes', odorFamily: 'Herbal', costPerGram: 0.25, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-121', name: 'Thyme Essential Oil', cas: '8007-46-3', category: 'Top Notes', odorFamily: 'Herbal', costPerGram: 0.22, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-122', name: 'Sage Essential Oil', cas: '8022-56-8', category: 'Heart Notes', odorFamily: 'Herbal', costPerGram: 0.28, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-123', name: 'Bay Leaf Essential Oil', cas: '8006-78-8', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.32, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-124', name: 'Pimento Berry Essential Oil', cas: '8016-45-3', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.38, ifraMax: 4, natural: true, inStock: true },
    { id: 'm-125', name: 'Juniper Berry Essential Oil', cas: '8012-91-7', category: 'Top Notes', odorFamily: 'Woody', costPerGram: 0.35, ifraMax: 10, natural: true, inStock: true },
    { id: 'm-126', name: 'Pine Needle Essential Oil', cas: '8000-26-8', category: 'Top Notes', odorFamily: 'Woody', costPerGram: 0.16, ifraMax: 14, natural: true, inStock: true },
    { id: 'm-127', name: 'Cypress Essential Oil', cas: '8013-86-3', category: 'Heart Notes', odorFamily: 'Woody', costPerGram: 0.20, ifraMax: 12, natural: true, inStock: true },
    { id: 'm-128', name: 'Fir Balsam Essential Oil', cas: '8021-28-1', category: 'Top Notes', odorFamily: 'Woody', costPerGram: 0.22, ifraMax: 12, natural: true, inStock: true },
    { id: 'm-129', name: 'Atlas Cedar Essential Oil', cas: '8000-27-2', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.20, ifraMax: 14, natural: true, inStock: true },
    { id: 'm-130', name: 'Himalayan Cedar Essential Oil', cas: '8000-27-2', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.25, ifraMax: 14, natural: true, inStock: true },
    { id: 'm-131', name: 'Rosewood Essential Oil', cas: '8015-77-8', category: 'Heart Notes', odorFamily: 'Woody', costPerGram: 0.40, ifraMax: 10, natural: true, inStock: true },
    { id: 'm-132', name: 'Teakwood Essential Oil', cas: '8015-89-2', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.55, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-133', name: 'Guaiacwood Essential Oil', cas: '8016-23-7', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.45, ifraMax: 10, natural: true, inStock: true },
    { id: 'm-134', name: 'Agarwood Essential Oil', cas: '94334-08-4', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 12.50, ifraMax: 2, natural: true, inStock: true },
    { id: 'm-135', name: 'Copaiba Balsam Essential Oil', cas: '8001-61-4', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.30, ifraMax: 10, natural: true, inStock: true },
    { id: 'm-136', name: 'Elemi Resinoid', cas: '8023-82-3', category: 'Heart Notes', odorFamily: 'Citrus', costPerGram: 0.50, ifraMax: 8, natural: true, inStock: true },
    { id: 'm-137', name: 'Styrax Resinoid', cas: '8046-19-3', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.65, ifraMax: 6, natural: true, inStock: true },
    { id: 'm-138', name: 'Castoreum Synthetic', cas: '100-42-5', category: 'Base Notes', odorFamily: 'Animalic', costPerGram: 0.50, ifraMax: 3, natural: false, inStock: true },
    { id: 'm-139', name: 'Civet Synthetic', cas: '100-42-5', category: 'Base Notes', odorFamily: 'Animalic', costPerGram: 0.60, ifraMax: 2, natural: false, inStock: true },
    { id: 'm-140', name: 'Hyraceum Tincture', cas: '100-42-5', category: 'Base Notes', odorFamily: 'Animalic', costPerGram: 0.80, ifraMax: 2, natural: false, inStock: true },
    { id: 'm-141', name: 'Ambroxide', cas: '6790-58-5', category: 'Base Notes', odorFamily: 'Amber', costPerGram: 1.80, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-142', name: 'Cetalox', cas: '373-72-8', category: 'Base Notes', odorFamily: 'Amber', costPerGram: 1.20, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-143', name: 'Norlimbanol', cas: '70788-30-6', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 2.40, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-144', name: 'Timbersilk', cas: '54464-57-2', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.08, ifraMax: 30, natural: false, inStock: true },
    { id: 'm-145', name: 'Sylvamber', cas: '54464-57-2', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.12, ifraMax: 25, natural: false, inStock: true },
    { id: 'm-146', name: 'Cashmeran', cas: '33704-61-9', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.35, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-147', name: 'Exaltolide', cas: '106-02-5', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.45, ifraMax: 15, natural: false, inStock: true },
    { id: 'm-148', name: 'Habanolide', cas: '34902-57-3', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.28, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-149', name: 'Muscenone', cas: '64878-01-7', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.55, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-150', name: 'Musc T', cas: '3391-86-8', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.38, ifraMax: 14, natural: false, inStock: true },
    { id: 'm-151', name: 'Velvione', cas: '37609-25-9', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.65, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-152', name: 'Helvetolide', cas: '141773-73-1', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.42, ifraMax: 14, natural: false, inStock: true },
    { id: 'm-153', name: 'Serenolide', cas: '107724-88-9', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.48, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-154', name: 'Romandolide', cas: '236391-76-7', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.50, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-155', name: 'Ethylene Brassylate', cas: '105-95-3', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.15, ifraMax: 25, natural: false, inStock: true },
    { id: 'm-156', name: 'Aldehyde C-10', cas: '112-31-2', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.12, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-157', name: 'Aldehyde C-11', cas: '112-44-7', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.14, ifraMax: 5, natural: false, inStock: true },
    { id: 'm-158', name: 'Aldehyde C-12 MNA', cas: '110-41-8', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.16, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-159', name: 'Aldehyde C-12 Lauric', cas: '112-54-9', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.15, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-160', name: 'Aldehyde C-14 Gamma', cas: '104-67-6', category: 'Heart Notes', odorFamily: 'Fruity', costPerGram: 0.18, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-161', name: 'Aldehyde C-16 Gamma', cas: '3658-77-3', category: 'Heart Notes', odorFamily: 'Fruity', costPerGram: 0.20, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-162', name: 'Aldehyde C-18 Gamma', cas: '104-61-0', category: 'Heart Notes', odorFamily: 'Fruity', costPerGram: 0.22, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-163', name: 'Schiff Base Aurantine', cas: '89-43-0', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.18, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-164', name: 'Schiff Base Verdantiol', cas: '89-43-0', category: 'Heart Notes', odorFamily: 'Green', costPerGram: 0.22, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-165', name: 'Dihydromyrcenol', cas: '18479-58-8', category: 'Top Notes', odorFamily: 'Citrus', costPerGram: 0.06, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-166', name: 'Linalyl Acetate', cas: '115-95-7', category: 'Top Notes', odorFamily: 'Floral', costPerGram: 0.05, ifraMax: 25, natural: false, inStock: true },
    { id: 'm-167', name: 'Tetrahydrolinalool', cas: '78-69-3', category: 'Top Notes', odorFamily: 'Floral', costPerGram: 0.06, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-168', name: 'Benzyl Salicylate', cas: '118-58-1', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.07, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-169', name: 'Amyl Salicylate', cas: '2050-08-0', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.08, ifraMax: 18, natural: false, inStock: true },
    { id: 'm-170', name: 'Hexyl Salicylate', cas: '6259-76-3', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.08, ifraMax: 18, natural: false, inStock: true },
    { id: 'm-171', name: 'Methyl Salicylate', cas: '119-36-8', category: 'Top Notes', odorFamily: 'Minty', costPerGram: 0.05, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-172', name: 'Ethyl Acetoacetate', cas: '141-97-9', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.03, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-173', name: 'Allyl Caproate', cas: '123-68-2', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.12, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-174', name: 'Ethyl Caproate', cas: '123-66-0', category: 'Top Notes', odorFamily: 'Fruity', costPerGram: 0.06, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-175', name: 'Ethyl Oenanthate', cas: '106-30-9', category: 'Heart Notes', odorFamily: 'Fruity', costPerGram: 0.08, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-176', name: 'Phenylacetaldehyde', cas: '122-78-1', category: 'Heart Notes', odorFamily: 'Green', costPerGram: 0.15, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-177', name: 'Phenylacetic Acid', cas: '103-82-2', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.10, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-178', name: 'Phenoxyethyl Isobutyrate', cas: '103-60-6', category: 'Heart Notes', odorFamily: 'Fruity', costPerGram: 0.08, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-179', name: 'Methyl Phenylacetate', cas: '101-41-7', category: 'Heart Notes', odorFamily: 'Sweet', costPerGram: 0.10, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-180', name: 'Ethyl Phenylacetate', cas: '101-97-3', category: 'Heart Notes', odorFamily: 'Sweet', costPerGram: 0.09, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-181', name: 'Gamma Decalactone', cas: '706-14-9', category: 'Base Notes', odorFamily: 'Fruity', costPerGram: 0.30, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-182', name: 'Gamma Undecalactone', cas: '104-67-6', category: 'Base Notes', odorFamily: 'Fruity', costPerGram: 0.35, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-183', name: 'Gamma Dodecalactone', cas: '2305-05-7', category: 'Base Notes', odorFamily: 'Fruity', costPerGram: 0.28, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-184', name: 'Delta Decalactone', cas: '705-86-2', category: 'Base Notes', odorFamily: 'Fruity', costPerGram: 0.32, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-185', name: 'Delta Dodecalactone', cas: '713-95-1', category: 'Base Notes', odorFamily: 'Fruity', costPerGram: 0.30, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-186', name: 'Nonadienol', cas: '10339-61-4', category: 'Top Notes', odorFamily: 'Green', costPerGram: 0.45, ifraMax: 2, natural: false, inStock: true },
    { id: 'm-187', name: 'Octenol', cas: '3391-86-8', category: 'Top Notes', odorFamily: 'Earthy', costPerGram: 0.35, ifraMax: 2, natural: false, inStock: true },
    { id: 'm-188', name: 'Geosmin', cas: '19700-21-1', category: 'Base Notes', odorFamily: 'Earthy', costPerGram: 5.50, ifraMax: 0.5, natural: false, inStock: true },
    { id: 'm-189', name: 'Isobutyl Quinoline', cas: '93-19-6', category: 'Base Notes', odorFamily: 'Animalic', costPerGram: 0.60, ifraMax: 2, natural: false, inStock: true },
    { id: 'm-190', name: 'Indole', cas: '120-72-9', category: 'Heart Notes', odorFamily: 'Animalic', costPerGram: 0.40, ifraMax: 1, natural: false, inStock: true },
    { id: 'm-191', name: 'Skatole', cas: '83-34-1', category: 'Base Notes', odorFamily: 'Animalic', costPerGram: 0.55, ifraMax: 0.5, natural: false, inStock: true },
    { id: 'm-192', name: 'Methyl Ionone Gamma', cas: '127-51-5', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.12, ifraMax: 16, natural: false, inStock: true },
    { id: 'm-193', name: 'Allyl Ionone', cas: '67634-01-9', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.18, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-194', name: 'Pentalide', cas: '106-02-5', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.50, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-195', name: 'Ambrettolide', cas: '28645-51-4', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.70, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-196', name: 'Globalide', cas: '34902-57-3', category: 'Base Notes', odorFamily: 'Musk', costPerGram: 0.45, ifraMax: 14, natural: false, inStock: true },
    { id: 'm-197', name: 'Ethyl Linalool', cas: '10339-55-6', category: 'Top Notes', odorFamily: 'Floral', costPerGram: 0.07, ifraMax: 20, natural: false, inStock: true },
    { id: 'm-198', name: 'Tetrahydrogeraniol', cas: '106-21-8', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.08, ifraMax: 18, natural: false, inStock: true },
    { id: 'm-199', name: 'Borneol', cas: '507-70-0', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.15, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-200', name: 'Isoborneol', cas: '124-76-5', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.14, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-201', name: 'Nerolidol', cas: '7212-44-4', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.10, ifraMax: 14, natural: false, inStock: true },
    { id: 'm-202', name: 'Farnesyl Acetate', cas: '29548-30-9', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.20, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-203', name: 'Cedryl Acetate', cas: '77-54-3', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.18, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-204', name: 'Vetiveryl Acetate', cas: '62563-69-1', category: 'Base Notes', odorFamily: 'Woody', costPerGram: 0.35, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-205', name: 'Styrallyl Acetate', cas: '93-92-5', category: 'Heart Notes', odorFamily: 'Green', costPerGram: 0.12, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-206', name: 'Dimethylbenzyl Carbinol', cas: '100-86-7', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.10, ifraMax: 14, natural: false, inStock: true },
    { id: 'm-207', name: 'Dimethylbenzyl Carbinyl Acetate', cas: '151-05-3', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.12, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-208', name: 'Trichloromethyl Phenyl Carbinyl Acetate', cas: '90-17-5', category: 'Heart Notes', odorFamily: 'Floral', costPerGram: 0.25, ifraMax: 6, natural: false, inStock: true },
    { id: 'm-209', name: 'Methyl Cinnamate', cas: '103-26-4', category: 'Heart Notes', odorFamily: 'Sweet', costPerGram: 0.08, ifraMax: 14, natural: false, inStock: true },
    { id: 'm-210', name: 'Ethyl Cinnamate', cas: '103-36-6', category: 'Heart Notes', odorFamily: 'Sweet', costPerGram: 0.09, ifraMax: 12, natural: false, inStock: true },
    { id: 'm-211', name: 'Benzyl Cinnamate', cas: '103-41-3', category: 'Base Notes', odorFamily: 'Sweet', costPerGram: 0.14, ifraMax: 10, natural: false, inStock: true },
    { id: 'm-212', name: 'Cinnamaldehyde', cas: '104-55-2', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.10, ifraMax: 4, natural: false, inStock: true },
    { id: 'm-213', name: 'Cinnamyl Alcohol', cas: '104-54-1', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.10, ifraMax: 8, natural: false, inStock: true },
    { id: 'm-214', name: 'Cinnamyl Acetate', cas: '103-54-8', category: 'Heart Notes', odorFamily: 'Spicy', costPerGram: 0.12, ifraMax: 8, natural: false, inStock: true },
  ],

  team: [
    { name: 'Sarah Chen', role: 'Senior Perfumer', avatar: null, status: 'active' },
    { name: 'Marcus Webb', role: 'R&D Director', avatar: null, status: 'active' },
    { name: 'Elena Rodriguez', role: 'Compliance Officer', avatar: null, status: 'away' },
    { name: 'James Park', role: 'AI Research Scientist', avatar: null, status: 'active' },
    { name: 'Olivia Tanaka', role: 'Junior Perfumer', avatar: null, status: 'offline' },
    { name: 'David Kim', role: 'Product Manager', avatar: null, status: 'active' },
    { name: 'Sophie Martin', role: 'Quality Control', avatar: null, status: 'active' },
    { name: 'Lucas Andersen', role: 'Supply Chain', avatar: null, status: 'away' },
  ],

  revenue: [
    { month: 'Jul 2025', value: 120000 },
    { month: 'Aug 2025', value: 145000 },
    { month: 'Sep 2025', value: 138000 },
    { month: 'Oct 2025', value: 182000 },
    { month: 'Nov 2025', value: 195000 },
    { month: 'Dec 2025', value: 210000 },
    { month: 'Jan 2026', value: 245000 },
    { month: 'Feb 2026', value: 268000 },
    { month: 'Mar 2026', value: 310000 },
    { month: 'Apr 2026', value: 355000 },
    { month: 'May 2026', value: 390000 },
    { month: 'Jun 2026', value: 412000 },
  ],

  customers: [
    { name: 'LVMH Fragrances', region: 'Europe', plan: 'Enterprise', mrr: 45000, since: 'Jul 2025' },
    { name: 'Chanel Parfums', region: 'Europe', plan: 'Enterprise', mrr: 42000, since: 'Aug 2025' },
    { name: 'Coty Inc.', region: 'North America', plan: 'Enterprise', mrr: 38000, since: 'Sep 2025' },
    { name: 'Puig', region: 'Europe', plan: 'Enterprise', mrr: 35000, since: 'Oct 2025' },
    { name: 'Firmenich', region: 'Europe', plan: 'Enterprise', mrr: 32000, since: 'Oct 2025' },
    { name: 'Givaudan', region: 'Europe', plan: 'Enterprise', mrr: 31000, since: 'Nov 2025' },
    { name: 'IFF', region: 'North America', plan: 'Enterprise', mrr: 30000, since: 'Nov 2025' },
    { name: 'Symrise', region: 'Europe', plan: 'Enterprise', mrr: 28000, since: 'Dec 2025' },
    { name: 'Takasago', region: 'Asia', plan: 'Business', mrr: 18000, since: 'Dec 2025' },
    { name: 'Mane', region: 'Europe', plan: 'Business', mrr: 15000, since: 'Jan 2026' },
    { name: 'Robertet', region: 'Europe', plan: 'Business', mrr: 14000, since: 'Jan 2026' },
    { name: 'Sensient', region: 'North America', plan: 'Business', mrr: 13000, since: 'Feb 2026' },
    { name: 'Aromatech', region: 'Europe', plan: 'Business', mrr: 12000, since: 'Feb 2026' },
    { name: 'Berjé', region: 'North America', plan: 'Business', mrr: 11000, since: 'Mar 2026' },
    { name: 'Vigon', region: 'North America', plan: 'Business', mrr: 10000, since: 'Mar 2026' },
    { name: 'Pell Wall', region: 'Europe', plan: 'Starter', mrr: 5000, since: 'Apr 2026' },
    { name: 'De Monchy', region: 'Europe', plan: 'Starter', mrr: 4800, since: 'Apr 2026' },
    { name: 'Esperis', region: 'Europe', plan: 'Starter', mrr: 4500, since: 'Apr 2026' },
    { id: 'c-019', name: 'Moellhausen', region: 'Europe', plan: 'Starter', mrr: 4200, since: 'May 2026' },
    { id: 'c-020', name: 'Aromaland', region: 'Asia', plan: 'Starter', mrr: 4000, since: 'May 2026' },
    { id: 'c-021', name: 'Phoenix Aromas', region: 'North America', plan: 'Starter', mrr: 3800, since: 'May 2026' },
    { id: 'c-022', name: 'Aroma Works', region: 'Asia', plan: 'Starter', mrr: 3600, since: 'Jun 2026' },
    { id: 'c-023', name: 'Fragrance Oils', region: 'Europe', plan: 'Starter', mrr: 3400, since: 'Jun 2026' },
    { id: 'c-024', name: 'New Directions', region: 'North America', plan: 'Starter', mrr: 3200, since: 'Jun 2026' },
  ],

  predictions: { today: 12847, accuracy: 98.5, total: 2840000 },
  modelHealth: [
    { name: 'Quality Predictor', status: 'healthy', accuracy: 96.2, latency: 45 },
    { name: 'Cost Optimizer', status: 'healthy', accuracy: 94.8, latency: 120 },
    { name: 'IFRA Classifier', status: 'healthy', accuracy: 99.1, latency: 32 },
    { name: 'Performance Forecaster', status: 'degraded', accuracy: 88.5, latency: 78 },
  ],

  activities: [
    { user: 'Sarah Chen', action: 'created formula', target: 'Solaire de Nuit', time: '2 min ago', type: 'create' },
    { user: 'Marcus Webb', action: 'approved formula', target: 'Jardin Céleste', time: '15 min ago', type: 'approve' },
    { user: 'James Park', action: 'ran AI optimization on', target: 'Ambre Révélation', time: '32 min ago', type: 'ai' },
    { user: 'Elena Rodriguez', action: 'flagged IFRA violation in', target: 'Bois Mystique', time: '1 hour ago', type: 'warning' },
    { user: 'Olivia Tanaka', action: 'updated material', target: 'Bergamot Essential Oil', time: '2 hours ago', type: 'update' },
    { user: 'David Kim', action: 'added project', target: 'Summer Collection 2027', time: '3 hours ago', type: 'create' },
    { user: 'Sophie Martin', action: 'completed QC check on', target: 'Rose de Damas', time: '4 hours ago', type: 'approve' },
    { user: 'Sarah Chen', action: 'submitted formula for review', target: 'Cuir Impérial', time: '5 hours ago', type: 'create' },
    { user: 'Lucas Andersen', action: 'updated inventory for', target: 'Sandalwood Oil', time: '6 hours ago', type: 'update' },
    { user: 'Marcus Webb', action: 'generated report', target: 'Q2 2026 R&D Summary', time: '7 hours ago', type: 'create' },
    { user: 'James Park', action: 'deployed model', target: 'v2.4 Quality Predictor', time: '8 hours ago', type: 'ai' },
    { user: 'Elena Rodriguez', action: 'completed audit', target: 'REACH Compliance Check', time: '9 hours ago', type: 'approve' },
    { user: 'Olivia Tanaka', action: 'created formula', target: 'Fleur de Nacre', time: '10 hours ago', type: 'create' },
    { user: 'David Kim', action: 'updated project status', target: 'Winter Collection', time: '11 hours ago', type: 'update' },
    { user: 'Sophie Martin', action: 'flagged quality issue in', target: 'Patchouli Batch #482', time: '12 hours ago', type: 'warning' },
    { user: 'Sarah Chen', action: 'submitted formula for review', target: 'Oud Royale', time: '13 hours ago', type: 'create' },
    { user: 'Marcus Webb', action: 'approved material', target: 'Ambergris Synthetic', time: '14 hours ago', type: 'approve' },
    { user: 'James Park', action: 'ran AI prediction on', target: 'Santal Éternel', time: '15 hours ago', type: 'ai' },
    { user: 'Lucas Andersen', action: 'restocked material', target: 'Vanilla Absolute', time: '16 hours ago', type: 'update' },
    { user: 'Elena Rodriguez', action: 'updated IFRA standards', target: '50th Amendment', time: '17 hours ago', type: 'update' },
    { user: 'Olivia Tanaka', action: 'created formula', target: 'Brise Méditerranéenne v3', time: '18 hours ago', type: 'create' },
    { user: 'David Kim', action: 'added customer', target: 'Aroma Works GmbH', time: '19 hours ago', type: 'create' },
    { user: 'Sophie Martin', action: 'completed QC check on', target: 'Vanille des Îles', time: '20 hours ago', type: 'approve' },
    { user: 'Sarah Chen', action: 'submitted formula for review', target: 'Tabac Doré', time: '21 hours ago', type: 'create' },
    { user: 'Marcus Webb', action: 'generated report', target: 'Material Cost Analysis', time: '22 hours ago', type: 'create' },
    { user: 'James Park', action: 'updated model parameters', target: 'Cost Optimizer v3', time: '23 hours ago', type: 'ai' },
    { user: 'Elena Rodriguez', action: 'completed audit', target: 'CLP Labeling Check', time: '1 day ago', type: 'approve' },
    { user: 'Olivia Tanaka', action: 'updated formula', target: 'Nuit Étoilée', time: '1 day ago', type: 'update' },
    { user: 'Lucas Andersen', action: 'ordered material', target: 'Jasmine Absolute 5kg', time: '1 day ago', type: 'update' },
    { user: 'David Kim', action: 'updated project status', target: 'Spring Collection', time: '1 day ago', type: 'update' },
    { user: 'Sarah Chen', action: 'created formula', target: 'Fève Tonka d\'Amazonie', time: '1 day ago', type: 'create' },
    { user: 'Marcus Webb', action: 'approved formula', target: 'Encens Sacré v2', time: '1 day ago', type: 'approve' },
    { user: 'Sophie Martin', action: 'flagged quality issue in', target: 'Ylang Ylang Batch #91', time: '1 day ago', type: 'warning' },
    { user: 'James Park', action: 'deployed model', target: 'v1.8 IFRA Classifier', time: '1 day ago', type: 'ai' },
    { user: 'Elena Rodriguez', action: 'created compliance report', target: 'Monthly IFRA Summary', time: '1 day ago', type: 'create' },
    { user: 'Olivia Tanaka', action: 'created formula', target: 'Agrumes de Sicile', time: '1 day ago', type: 'create' },
    { user: 'Lucas Andersen', action: 'updated supplier info', target: 'Symrise AG', time: '2 days ago', type: 'update' },
    { user: 'David Kim', action: 'added team member', target: 'Ana Costa', time: '2 days ago', type: 'create' },
    { user: 'Sarah Chen', action: 'submitted formula for review', target: 'Patchouli Intense', time: '2 days ago', type: 'create' },
    { user: 'Marcus Webb', action: 'generated report', target: 'Supplier Performance Q2', time: '2 days ago', type: 'create' },
    { user: 'James Park', action: 'ran AI prediction on', target: 'Bois de Santal Australien', time: '2 days ago', type: 'ai' },
    { user: 'Sophie Martin', action: 'completed QC check on', target: 'Lavande Provence Batch #3', time: '2 days ago', type: 'approve' },
    { user: 'Elena Rodriguez', action: 'updated regulation', target: 'EU Cosmetics Regulation', time: '2 days ago', type: 'update' },
    { user: 'Olivia Tanaka', action: 'updated formula', target: 'Géranium Bourbon', time: '2 days ago', type: 'update' },
    { user: 'Sarah Chen', action: 'created formula', target: 'Magnolia du Sud', time: '3 days ago', type: 'create' },
    { user: 'Marcus Webb', action: 'approved material', target: 'Oud Royal Essential Oil', time: '3 days ago', type: 'approve' },
    { user: 'James Park', action: 'completed training run', target: 'Performance Forecaster v4', time: '3 days ago', type: 'ai' },
    { user: 'David Kim', action: 'updated roadmap', target: 'Q3 2026 Product Roadmap', time: '3 days ago', type: 'update' },
    { user: 'Lucas Andersen', action: 'restocked material', target: 'Sandalwood Oil 10kg', time: '3 days ago', type: 'update' },
    { user: 'Elena Rodriguez', action: 'completed audit', target: 'All Formulas IFRA Check', time: '3 days ago', type: 'approve' },
  ],

  ifraCategories: [
    { name: 'Compliant', value: 42 },
    { name: 'Warning', value: 8 },
    { name: 'Violation', value: 2 },
  ],

  formulaStatuses: [
    { status: 'Approved', count: 22 },
    { status: 'In Review', count: 14 },
    { status: 'Draft', count: 13 },
    { status: 'Rejected', count: 3 },
  ],

  pipeline: [
    { stage: 'Brief Received', count: 8, value: 0 },
    { stage: 'Formulation', count: 14, value: 0 },
    { stage: 'In Review', count: 10, value: 0 },
    { stage: 'QC Testing', count: 6, value: 0 },
    { stage: 'Approved', count: 4, value: 0 },
  ],
}

export const dashboardData = {
  arr: { current: 4800000, previous: 3200000, trend: 'up' as const, change: 50 },
  mrr: { current: 412000, previous: 358000, trend: 'up' as const, change: 15 },
  customers: { total: 47, new: 8, churned: 2, trend: 'up' as const },
  predictions: { today: 12847, accuracy: 98.5, total: 2840000 },
  compliance: { score: 94, ifraCompliance: 96, pending: 3, restrictedSubstitutions: 12 },
  formulaSuccess: { rate: 87, total: 520, aiGenerated: 180, avgTime: 3.2 },
  gpu: { utilization: 72, memory: 68, activeJobs: 4, queueDepth: 2 },
  revenueTrend: [
    { month: 'Jan', starter: 5000, professional: 25000, business: 75000, enterprise: 100000 },
    { month: 'Feb', starter: 5500, professional: 28000, business: 82000, enterprise: 110000 },
    { month: 'Mar', starter: 6200, professional: 31000, business: 88000, enterprise: 125000 },
    { month: 'Apr', starter: 6800, professional: 35000, business: 95000, enterprise: 140000 },
    { month: 'May', starter: 7500, professional: 39000, business: 105000, enterprise: 160000 },
    { month: 'Jun', starter: 8200, professional: 42000, business: 115000, enterprise: 185000 },
    { month: 'Jul', starter: 9100, professional: 48000, business: 128000, enterprise: 210000 },
    { month: 'Aug', starter: 9800, professional: 52000, business: 140000, enterprise: 240000 },
    { month: 'Sep', starter: 10500, professional: 58000, business: 155000, enterprise: 275000 },
    { month: 'Oct', starter: 11500, professional: 64000, business: 170000, enterprise: 310000 },
    { month: 'Nov', starter: 12800, professional: 72000, business: 190000, enterprise: 350000 },
    { month: 'Dec', starter: 14000, professional: 80000, business: 210000, enterprise: 400000 },
  ],
  customerGrowth: [
    { month: 'Jan', total: 12, new: 3, churned: 1 },
    { month: 'Feb', total: 14, new: 2, churned: 0 },
    { month: 'Mar', total: 18, new: 4, churned: 0 },
    { month: 'Apr', total: 21, new: 3, churned: 0 },
    { month: 'May', total: 25, new: 5, churned: 1 },
    { month: 'Jun', total: 30, new: 5, churned: 0 },
    { month: 'Jul', total: 33, new: 4, churned: 1 },
    { month: 'Aug', total: 36, new: 3, churned: 0 },
    { month: 'Sep', total: 39, new: 4, churned: 1 },
    { month: 'Oct', total: 42, new: 3, churned: 0 },
    { month: 'Nov', total: 45, new: 4, churned: 1 },
    { month: 'Dec', total: 47, new: 3, churned: 1 },
  ],
  modelHealth: [
    { name: 'Quality Predictor', driftScore: 0.02, lastTrained: '2026-06-15', accuracy: 97.2, status: 'healthy' as const },
    { name: 'Longevity Model', driftScore: 0.08, lastTrained: '2026-06-10', accuracy: 95.8, status: 'warning' as const },
    { name: 'IFRA Classifier', driftScore: 0.01, lastTrained: '2026-06-20', accuracy: 99.1, status: 'healthy' as const },
    { name: 'Similarity Engine', driftScore: 0.15, lastTrained: '2026-05-28', accuracy: 93.4, status: 'critical' as const },
    { name: 'Cost Optimizer', driftScore: 0.04, lastTrained: '2026-06-18', accuracy: 96.8, status: 'healthy' as const },
    { name: 'Accord Recommender', driftScore: 0.11, lastTrained: '2026-06-05', accuracy: 94.2, status: 'warning' as const },
  ],
  topCustomers: [
    { name: 'Maison Aura', mrr: 45000, plan: 'Enterprise' as const, health: 92, trend: 'up' as const },
    { name: 'Fragrance Innovations', mrr: 25000, plan: 'Business' as const, health: 78, trend: 'up' as const },
    { name: 'Scentify Labs', mrr: 22000, plan: 'Business' as const, health: 85, trend: 'stable' as const },
    { name: 'Olfactory Studios', mrr: 18000, plan: 'Professional' as const, health: 64, trend: 'down' as const },
    { name: 'Aroma Collective', mrr: 15000, plan: 'Professional' as const, health: 91, trend: 'up' as const },
  ],
  expansion: { opportunities: 8, pipeline: 320000, upgrades: 3, thisMonth: 45000 },
  activities: [
    { id: '1', user: 'Sarah Chen', action: 'created formula', target: 'Floral Bloom v3', timestamp: '2 min ago', type: 'formula' as const },
    { id: '2', user: 'James Wilson', action: 'approved formula', target: 'Ocean Mist v2', timestamp: '5 min ago', type: 'approval' as const },
    { id: '3', user: 'Maria Lopez', action: 'ran prediction', target: 'Woody Elegance', timestamp: '8 min ago', type: 'prediction' as const },
    { id: '4', user: 'AI System', action: 'completed training', target: 'Longevity Model v4', timestamp: '12 min ago', type: 'system' as const },
    { id: '5', user: 'Dr. Chen', action: 'updated formula', target: 'Citrus Burst v5', timestamp: '15 min ago', type: 'formula' as const },
    { id: '6', user: 'Sarah Chen', action: 'submitted review', target: 'Rose Noir v1', timestamp: '18 min ago', type: 'review' as const },
    { id: '7', user: 'AI System', action: 'detected drift', target: 'Similarity Engine', timestamp: '22 min ago', type: 'alert' as const },
    { id: '8', user: 'Maria Lopez', action: 'created formula', target: 'Vanilla Dream v1', timestamp: '25 min ago', type: 'formula' as const },
    { id: '9', user: 'James Wilson', action: 'modified material', target: 'Bergamot FCF', timestamp: '30 min ago', type: 'material' as const },
    { id: '10', user: 'AI System', action: 'generated suggestion', target: 'Jasmine Alternative', timestamp: '35 min ago', type: 'system' as const },
    { id: '11', user: 'Sarah Chen', action: 'exported report', target: 'Q2 Performance', timestamp: '40 min ago', type: 'report' as const },
    { id: '12', user: 'Dr. Chen', action: 'approved formula', target: 'Amber Supreme v3', timestamp: '45 min ago', type: 'approval' as const },
    { id: '13', user: 'Maria Lopez', action: 'ran prediction', target: 'Fresh Linen v2', timestamp: '48 min ago', type: 'prediction' as const },
    { id: '14', user: 'James Wilson', action: 'created formula', target: 'Tabac Noble v1', timestamp: '52 min ago', type: 'formula' as const },
    { id: '15', user: 'AI System', action: 'completed training', target: 'Quality Predictor v6', timestamp: '55 min ago', type: 'system' as const },
    { id: '16', user: 'Sarah Chen', action: 'reviewed compliance', target: 'IFRA 51st Amendment', timestamp: '58 min ago', type: 'compliance' as const },
    { id: '17', user: 'Maria Lopez', action: 'updated formula', target: 'Lavender Fields v4', timestamp: '1 hour ago', type: 'formula' as const },
    { id: '18', user: 'Dr. Chen', action: 'ran prediction', target: 'Musk Aura v1', timestamp: '1 hour ago', type: 'prediction' as const },
    { id: '19', user: 'AI System', action: 'generated suggestion', target: 'Sandalwood Substitute', timestamp: '1 hour ago', type: 'system' as const },
    { id: '20', user: 'James Wilson', action: 'created formula', target: 'Cedar & Sage v1', timestamp: '1 hour ago', type: 'formula' as const },
  ],
  arrSparkline: [2800000, 2950000, 3100000, 3200000, 3400000, 3600000, 3800000, 4000000, 4200000, 4400000, 4600000, 4800000],
  mrrSparkline: [358000, 362000, 368000, 372000, 378000, 385000, 390000, 395000, 401000, 405000, 409000, 412000],
  predictionSparkline: [8900, 9200, 9500, 9800, 10100, 10400, 10800, 11200, 11600, 12000, 12400, 12847],
  customerSparkline: [12, 14, 18, 21, 25, 30, 33, 36, 39, 42, 45, 47],
}
