export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  DASHBOARD_EXECUTIVE: '/dashboard/executive',
  DASHBOARD_PERFUMER: '/dashboard/perfumer',
  DASHBOARD_RD: '/dashboard/rd',
  DASHBOARD_OPERATIONS: '/dashboard/operations',
  DASHBOARD_AI: '/dashboard/ai',
  DASHBOARD_COMPLIANCE: '/dashboard/compliance',
  ADMIN_USERS: '/admin/users',
  ADMIN_TEAMS: '/admin/teams',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_BILLING: '/admin/billing',
  ADMIN_API_KEYS: '/admin/api-keys',
  ADMIN_AUDIT_TRAIL: '/admin/audit-trail',
  ADMIN_SSO: '/admin/sso',
  FORMULATION_STUDIO: '/formulation-studio',
  FORMULATIONS_LIBRARY: '/formulations/library',
  FORMULATIONS_WIZARD: '/formulations/wizard',
  FORMULATIONS_ARCHIVED: '/formulations/archived',
  MATERIALS_CATALOG: '/materials/catalog',
  MATERIALS_INVENTORY: '/materials/inventory',
  MATERIALS_SUPPLIERS: '/materials/suppliers',
  MATERIALS_PRICING: '/materials/pricing',
  MATERIALS_BATCH: '/materials/batch',
  MATERIALS_ALTERNATIVES: '/materials/alternatives',
  AI_LAB: '/ai-lab',
  AI_LAB_TRAINING: '/ai-lab/training',
  AI_LAB_PREDICTIONS: '/ai-lab/predictions',
  AI_LAB_MODELS: '/ai-lab/models',
  AI_LAB_EMBEDDINGS: '/ai-lab/embeddings',
  AI_LAB_SIMILARITY: '/ai-lab/similarity-explorer',
  AI_LAB_SEMANTIC: '/ai-lab/semantic-search',
  AI_LAB_OPTIMIZATION: '/ai-lab/optimization',
  AI_LAB_EXPERIMENTS: '/ai-lab/experiments',
  AI_LAB_DATASETS: '/ai-lab/datasets',
  AI_LAB_FEATURES: '/ai-lab/features',
  AI_LAB_EXPLAINABILITY: '/ai-lab/explainability',
  AI_LAB_INFERENCE: '/ai-lab/inference',
  AI_LAB_RECOMMENDATIONS: '/ai-lab/recommendation-center',
  SUPER_INTELLIGENCE: '/super-intelligence',
  PROJECTS_PLANNING: '/projects/planning',
  PROJECTS_ACTIVE: '/projects/active',
  PROJECTS_COMPLETED: '/projects/completed',
  COMPLIANCE_SDS: '/compliance/sds',
  COMPLIANCE_IFRA: '/compliance/ifra',
  COMPLIANCE_REACH: '/compliance/reach',
  COMPLIANCE_CLP: '/compliance/clp',
  COMPLIANCE_CERTIFICATES: '/compliance/certificates',
  COMPLIANCE_ALERTS: '/compliance/alerts',
  COMPLIANCE_AUDIT: '/compliance/audit-logs',
  ANALYTICS_PERFORMANCE: '/analytics/performance',
  ANALYTICS_TRENDS: '/analytics/trends',
  ANALYTICS_REPORTS: '/analytics/reports',
  ANALYTICS_EXPORT: '/analytics/export',
  SETTINGS_PROFILE: '/settings/profile',
  SETTINGS_PREFERENCES: '/settings/preferences',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_INTEGRATIONS: '/settings/integrations',
  SETTINGS_DATA: '/settings/data',
  ONBOARDING: '/onboarding',
  BILLING: '/billing',
  PRICING: '/pricing',
  TUTORIALS: '/tutorials',
  KNOWLEDGE_BASE: '/knowledge-base',
  ENTERPRISE: '/enterprise',
  ROI_CALCULATOR: '/roi-calculator',
  INVESTOR: '/investor',
  INVESTOR_LOGIN: '/investor/login',
  INVESTOR_DASHBOARD: '/investor/dashboard',
  EXPLORER: '/explorer',
  ALPHA: '/alpha',
  ALPHA_WAITLIST: '/alpha/waitlist',
  ALPHA_FEEDBACK: '/alpha/feedback',
  ALPHA_BUGS: '/alpha/bugs',
  ALPHA_ROADMAP: '/alpha/roadmap',
  DEMO_GENERATOR: '/demo-generator',
  INTELLIGENCE: '/intelligence',
  INTELLIGENCE_ACCELERATOR: '/intelligence/accelerator',
  INTELLIGENCE_COMPLIANCE: '/intelligence/compliance',
  INTELLIGENCE_KNOWLEDGE: '/intelligence/knowledge-vault',
  INTELLIGENCE_MATERIALS: '/intelligence/materials',
  INTELLIGENCE_EXPERIMENTS: '/intelligence/experiments',
  INTELLIGENCE_PREDICTOR: '/intelligence/success-predictor',
  INTELLIGENCE_REPORTS: '/intelligence/reports',
  INTELLIGENCE_INGESTION: '/intelligence/data-ingestion',
} as const

export const PUBLIC_ROUTES = [
  ROUTES.HOME,
  ROUTES.LOGIN,
  ROUTES.SIGNUP,
  ROUTES.ALPHA,
  ROUTES.ALPHA_WAITLIST,
  ROUTES.ALPHA_FEEDBACK,
  ROUTES.ALPHA_BUGS,
  ROUTES.ALPHA_ROADMAP,
  ROUTES.PRICING,
  ROUTES.ROI_CALCULATOR,
  ROUTES.TUTORIALS,
  ROUTES.KNOWLEDGE_BASE,
  ROUTES.ENTERPRISE,
  ROUTES.INVESTOR,
  ROUTES.INVESTOR_LOGIN,
]

export const ROUTE_LABELS: Record<string, string> = {
  [ROUTES.DASHBOARD]: 'Dashboard',
  [ROUTES.DASHBOARD_EXECUTIVE]: 'Executive',
  [ROUTES.DASHBOARD_PERFUMER]: 'Perfumer',
  [ROUTES.DASHBOARD_RD]: 'R&D',
  [ROUTES.DASHBOARD_OPERATIONS]: 'Operations',
  [ROUTES.DASHBOARD_AI]: 'AI Dashboard',
  [ROUTES.DASHBOARD_COMPLIANCE]: 'Compliance',
  [ROUTES.ADMIN_USERS]: 'Users',
  [ROUTES.ADMIN_TEAMS]: 'Teams',
  [ROUTES.ADMIN_ROLES]: 'Roles',
  [ROUTES.ADMIN_BILLING]: 'Billing',
  [ROUTES.ADMIN_API_KEYS]: 'API Keys',
  [ROUTES.ADMIN_AUDIT_TRAIL]: 'Audit Trail',
  [ROUTES.FORMULATION_STUDIO]: 'Studio',
  [ROUTES.FORMULATIONS_LIBRARY]: 'Library',
  [ROUTES.FORMULATIONS_WIZARD]: 'Wizard',
  [ROUTES.MATERIALS_CATALOG]: 'Catalog',
  [ROUTES.MATERIALS_INVENTORY]: 'Inventory',
  [ROUTES.AI_LAB]: 'AI Lab',
  [ROUTES.AI_LAB_TRAINING]: 'Training',
  [ROUTES.AI_LAB_PREDICTIONS]: 'Predictions',
  [ROUTES.AI_LAB_MODELS]: 'Models',
  [ROUTES.SUPER_INTELLIGENCE]: 'Super Intelligence',
  [ROUTES.PROJECTS_ACTIVE]: 'Active',
  [ROUTES.SETTINGS_PROFILE]: 'Profile',
  [ROUTES.ONBOARDING]: 'Onboarding',
  [ROUTES.BILLING]: 'Billing',
  [ROUTES.PRICING]: 'Pricing',
  [ROUTES.TUTORIALS]: 'Tutorials',
  [ROUTES.KNOWLEDGE_BASE]: 'Knowledge Base',
}
